version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - 5601:5601
    
  # curl:
  #   image: curlimages/curl:8.00.1
  #   container_name: curl
  #   command: tail -F anyFile