version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic  

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.7.1
    environment:
      - config.reload.automatic=true
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./data/logstash:/usr/share/logstash/data
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/pattern:/usr/share/logstash/pattern
      - ./log_file/input:/usr/share/logs/input
      - ./log_file/output:/usr/share/logs/output
    networks:
      - elastic
    
  # curl:
  #   image: curlimages/curl:8.00.1
  #   container_name: curl
  #   command: tail -F anyFile
  #   volumes:
  #     - ./ndjson:/data/ndjson
  #   networks:
  #     - elastic
networks:
  elastic:
    driver: bridge