- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/logstash.conf"

- pipeline.id: apache
  path.config: "/usr/share/logstash/pipeline/apache_logstash.conf"

- pipeline.id: pattern
  path.config: "/usr/share/logstash/pipeline/pattern_logstash.conf"